[workspace]
cargo-features = ["edition2021"]

[package]
name = "gfx"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apng = "0.2.0"
nalgebra = "0.29"
png = "0.17.3"